# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Adding host and port here for development might be necessary if using TCP/IP connection
  # host: localhost
  # port: 5432

development:
  <<: *default
  database: mini_capstone_api_development
  # Uncomment and provide these if needed for local development:
  # username: your_local_db_username
  # password: your_local_db_password
  # host: localhost  # Usually default to Unix domain socket
  # port: 5432       # Default PostgreSQL port

test:
  <<: *default
  database: mini_capstone_api_test
  # Uncomment and provide these if needed for testing environment:
  # username: your_test_db_username
  # password: your_test_db_password
  # host: localhost
  # port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # This environment variable should include all connection details

  # Following configurations demonstrate multiple databases scenario in production.
  # Adjust accordingly if using multiple databases.
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %> # Ensures primary DB uses DATABASE_URL

  cache:
    <<: *primary_production
    database: mini_capstone_api_production_cache # Separate cache database if required
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: mini_capstone_api_production_queue # Separate queue database if required
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: mini_capstone_api_production_cable # Separate database for ActionCable if required
    migrations_paths: db/cable_migrate
